# Generated by Django 3.1.3 on 2020-12-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Programme', models.TextField()),
                ('University', models.TextField()),
                ('Programme_Fee', models.TextField()),
                ('Country', models.TextField()),
                ('Address', models.TextField()),
                ('Latitude', models.TextField()),
                ('Longitude', models.TextField()),
            ],
            options={
                'db_table': 'study',
            },
        ),
    ]
