# Generated by Django 3.1.3 on 2020-12-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='Programme_Fee',
            field=models.IntegerField(),
        ),
    ]
